name: Password

on: [push]

jobs:
  builds:

    runs-on: ubuntu-latest

    steps:
    - name: Print Password
      env:
        MY_PASSWORD: ${{ secrets.PASSWORD }}
      run: echo My password is $MY_PASSWORD
